In [2]:
import numpy as np
#PROBLEM1

arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#problem2

random_array = np.array(np.random.randint(10,45,(2,3,5)))
print(f"The defined array is \n{random_array}")
print(f" \n The shape of the array is {random_array.shape}")

The defined array is 
[[[21 27 29 40 40]
  [10 14 39 39 44]
  [34 36 23 25 33]]

 [[14 41 17 13 42]
  [10 37 32 36 29]
  [44 37 29 27 35]]]
 
 The shape of the array is (2, 3, 5)


In [10]:
#PROBLEM3

array1 = np.array(np.random.randint(10,21,(2,3,5)))
print(f"Array 1 is: \n{array1}")
print(f" \n The shape of the array is {array1.shape}")


array2 = np.array(np.random.randint(10,21,(1,3,5)))
print(f"Array 1 is: \n{array2}")
print(f" \n The shape of the array is {array2.shape}")

Array 1 is: 
[[[12 13 15 17 19]
  [17 14 17 16 10]
  [19 19 13 20 11]]

 [[11 14 16 16 10]
  [12 13 19 12 17]
  [13 18 13 10 15]]]
 
 The shape of the array is (2, 3, 5)
Array 1 is: 
[[[20 18 11 18 16]
  [19 11 11 18 17]
  [15 11 11 20 11]]]
 
 The shape of the array is (1, 3, 5)


In [16]:
#PROBLEM4
array_mult=np.multiply(array1,array2)
array_mult

array([[[240, 234, 165, 306, 304],
        [323, 154, 187, 288, 170],
        [285, 209, 143, 400, 121]],

       [[220, 252, 176, 288, 160],
        [228, 143, 209, 216, 289],
        [195, 198, 143, 200, 165]]])

In [14]:
print(np.min(array_mult,axis=1))

[[240 154 143 288 121]
 [195 143 143 200 160]]


In [17]:
print(np.sum(array_mult,axis=0))

[[460 486 341 594 464]
 [551 297 396 504 459]
 [480 407 286 600 286]]
